// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbjsi9fZXwlDMzsBH2M4XiOTG6PskUSss',
    appId: '1:168048754169:web:91953c7122a833576e1128',
    messagingSenderId: '168048754169',
    projectId: 'superhero-rendezvous',
    authDomain: 'superhero-rendezvous.firebaseapp.com',
    storageBucket: 'superhero-rendezvous.appspot.com',
    measurementId: 'G-NFNQ8X5G29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdiPfXtBk3J4DUPR_wes7AkEpKjSpmaVg',
    appId: '1:168048754169:android:408e876ed5e1872b6e1128',
    messagingSenderId: '168048754169',
    projectId: 'superhero-rendezvous',
    storageBucket: 'superhero-rendezvous.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmFe4bgNxvEsrQRJj57g4TUTAl6PJqLWk',
    appId: '1:168048754169:ios:12cf12e55de757d86e1128',
    messagingSenderId: '168048754169',
    projectId: 'superhero-rendezvous',
    storageBucket: 'superhero-rendezvous.appspot.com',
    iosClientId: '168048754169-1b881jnsq4hr21ufnv5dji1ht3hrt7ak.apps.googleusercontent.com',
    iosBundleId: 'com.datingapp.superheroRendezvous',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmFe4bgNxvEsrQRJj57g4TUTAl6PJqLWk',
    appId: '1:168048754169:ios:12cf12e55de757d86e1128',
    messagingSenderId: '168048754169',
    projectId: 'superhero-rendezvous',
    storageBucket: 'superhero-rendezvous.appspot.com',
    iosClientId: '168048754169-1b881jnsq4hr21ufnv5dji1ht3hrt7ak.apps.googleusercontent.com',
    iosBundleId: 'com.datingapp.superheroRendezvous',
  );
}
